### ISSUE TITLE
[Footer] Add Discord link

### ISSUE THREAD

**Issue by areeta** [hackuci/HackUCI-Site#26]
Can we add the Discord link? :))

<img width="970" alt="Screen Shot 2020-12-07 at 6 18 32 PM" src="https://user-images.githubusercontent.com/20546538/101429799-a0551300-38b8-11eb-9759-9676d2b1aded.png">

**Comment by ChaseC99** [comment]
We don't provide direct links to our Discord. Everyone that joins has to do it through the form on our website, so that ZotBot can set their Discord nickname to their real name.

So our options are:
1. Add a Discord icon that links to the form: https://hack.ics.uci.edu/#discord
2. Disable ZotBot and stop requiring people to join with their real name; Add a direct Discord link to the footer.
3. Not add a Discord link to the footer

**Comment by zpinto** [comment]
I think option 1 works best 😄
